### ISSUE TITLE
Problem with GoogleLighthouse

### ISSUE THREAD

**Issue by tigo17** [newrelic/quickstarts-synthetics-library#17]
Result Details
|
São Paulo, BR
Check failed with type error
Error
Expected value which is `predicate returns truthy for any value`, received values of types `null`.

Script log (11)
TypeError: Expected value which is `predicate returns truthy for any value`, received values of types `null`.
    at assertType (/app/synthetics-node-api-runtime/.yarn/cache/@sindresorhus-is-npm-4.6.0-7cad05c55e-83839f13da.zip/node_modules/@sindresorhus/is/dist/index.js:303:15)
    at Object.any (/app/synthetics-node-api-runtime/.yarn/cache/@sindresorhus-is-npm-4.6.0-7cad05c55e-83839f13da.zip/node_modules/@sindresorhus/is/dist/index.js:402:16)
    at normalizeArguments (/app/synthetics-node-api-runtime/.yarn/cache/got-npm-11.8.3-caf98d599b-3b6db107d9.zip/node_modules/got/dist/source/core/index.js:387:21)
    at got (/app/synthetics-node-api-runtime/.yarn/cache/got-npm-11.8.3-caf98d599b-3b6db107d9.zip/node_modules/got/dist/source/create.js:112:39)
    at doRequest (/app/synthetics-node-api-runtime/runtime/http/request-like-module.js:51:25)
    at DefaultRequest (/app/synthetics-node-api-runtime/runtime/http/request-like-module.js:47:10)
    at Object.eval [as run] (eval at buildSandbox (/app/synthetics-node-api-runtime/runtime/sandbox/runtime/environment.js:30:18), <anonymous>:17:1)
    at Object.runScript (/app/synthetics-node-api-runtime/runtime/sandbox/runtime/environment.js:36:24)
    at Object.run (/app/synthetics-node-api-runtime/runtime/sandbox/driver.js:10:23)
    at Object.run (/app/synthetics-node-api-runtime/runtime/driver/driver.js:7:22)

**Comment by tigo17** [comment]
I get this error when validate script on Synthetics in NewRelic.

**Comment by tigo17** [comment]
I selected Node 10 (Legacy) and work's fine. :)
![image](https://user-images.githubusercontent.com/8134568/173932272-3531c8c3-d3cf-4078-8559-ccc422e510e4.png)
